const pornstarComparisons = {
    cm: [
        { name: "Lexington Steele", length: 24.13 },
        { name: "Mandingo", length: 23.40 },
        { name: "Rocco Siffredi", length: 23.00 },
        { name: "Danny D", length: 22.86 },
        { name: "Julio Gomez", length: 23.89 },
        { name: "Criss Strokes", length: 22.86 },
        { name: "Manuel Ferrara", length: 21.59 },
        { name: "Kieran Lee", length: 22.23 },
        { name: "Vlad the Impaler", length: 23.50 },
        { name: "Whitezilla", length: 23.13 },
        { name: "Johnny Sins", length: 20.32 },
        { name: "James Deen", length: 19.05 },
        { name: "Keiran Lee", length: 22.86 },
        { name: "Mick Blue", length: 20.32 },
        { name: "Ramon Nomar", length: 21.59 },
        { name: "Bruce Venture", length: 20.32 },
        { name: "Jordi El Niño Polla", length: 17.78 },
        { name: "Small Hands", length: 16.51 },
        { name: "Xander Corvus", length: 18.42 },
        { name: "Seth Gamble", length: 17.78 },
        { name: "Mike Adriano", length: 16.51 },
        { name: "Tommy Gunn", length: 15.24 },
        { name: "Erik Everhard", length: 14.61 },
        { name: "Markus Dupree", length: 13.97 },
        { name: "Ricky Johnson", length: 13.34 },
        { name: "Damon Dice", length: 12.70 },
        { name: "Tyler Nixon", length: 12.07 },
        { name: "Logan Pierce", length: 11.43 },
        { name: "Alex D", length: 10.80 },
        { name: "Chad White", length: 10.16 },
        { name: "Brad Newman", length: 9.53 }
    ],
    in: [
        { name: "Lexington Steele", length: 9.5 },
        { name: "Mandingo", length: 9.2 },
        { name: "Rocco Siffredi", length: 9.0 },
        { name: "Danny D", length: 9.0 },
        { name: "Julio Gomez", length: 9.4 },
        { name: "Criss Strokes", length: 9.0 },
        { name: "Manuel Ferrara", length: 8.5 },
        { name: "Kieran Lee", length: 8.75 },
        { name: "Vlad the Impaler", length: 9.25 },
        { name: "Whitezilla", length: 9.1 },
        { name: "Johnny Sins", length: 8.0 },
        { name: "James Deen", length: 7.5 },
        { name: "Keiran Lee", length: 9.0 },
        { name: "Mick Blue", length: 8.0 },
        { name: "Ramon Nomar", length: 8.5 },
        { name: "Bruce Venture", length: 8.0 },
        { name: "Jordi El Niño Polla", length: 7.0 },
        { name: "Small Hands", length: 6.5 },
        { name: "Xander Corvus", length: 7.25 },
        { name: "Seth Gamble", length: 7.0 },
        { name: "Mike Adriano", length: 6.5 },
        { name: "Tommy Gunn", length: 6.0 },
        { name: "Erik Everhard", length: 5.75 },
        { name: "Markus Dupree", length: 5.5 },
        { name: "Ricky Johnson", length: 5.25 },
        { name: "Damon Dice", length: 5.0 },
        { name: "Tyler Nixon", length: 4.75 },
        { name: "Logan Pierce", length: 4.5 },
        { name: "Alex D", length: 4.25 },
        { name: "Chad White", length: 4.0 },
        { name: "Brad Newman", length: 3.75 }
    ]
};